const menu = [
  {
    id: 1,
    title: 'Nugat torta',
    category: 'torte',
    price: 4000,
    img: './images/item-1.jpg',
    desc: `Kora od čokolade sa kremom od Nutele, prelivena mlečnom čokoladom. Težina torte je 2kg.`,
  },
  {
    id: 2,
    title: 'Plazma torta',
    category: 'torte',
    price: 4400,
    img: './images/item-2.jpg',
    desc: `Kora sastavljena od plazme, oraha, soka od pomorandže, žele bombona i putera, sa šlagom. Težina torte je 2.2kg`,
  },
  {
    id: 3,
    title: 'Godzilla milksejk',
    category: 'šejkovi',
    price: 350,
    img: './images/item-3.jpeg',
    desc: `Ogroman šejk pun voca, mleka i slatkiša. Odličan za sve ljubitelje slatkiša.`,
  },
  {
    id: 4,
    title: 'Rafaelo torta',
    category: 'torte',
    price: 4400,
    img: './images/item-4.jpg',
    desc: `Bela korica sa kremom od kokosa i krupno mlevenog lešnika, prelivena belom čokoladom. Težina torte je 2kg. `,
  },
  {
    id: 5,
    title: 'Čizkejk',
    category: 'kolači',
    price: 350,
    img: './images/item-5.jpg',
    desc: `Kora od biskvita sa sokom od pomorandže i plazme i kremom od maskarpone sira i prelivom od jagode. `,
  },
  {
    id: 6,
    title: 'Oreo dream',
    category: 'šejkovi',
    price: 300,
    img: './images/item-6.jpeg',
    desc: `Šejk pun mleka i oreo keksa, odličan za letnje osveženje.`,
  },
  {
    id: 7,
    title: 'Čokoladna bombica kolač',
    category: 'kolači',
    price: 240,
    img: './images/item-7.jpg',
    desc: `Čokoladna bombica od čokoladnog krema i krupno mlevenih lešnika, prelivena tamnom čokoladom.`,
  },
  {
    id: 8,
    title: 'Bueno kolač',
    category: 'kolači',
    price: 350,
    img: './images/item-8.jpg',
    desc: `Čokoladna kora sa kremom od čokolade i lešnika i reda hrskavih lešnika, prelivena mlečnom čokoladom. `,
  },
  {
    id: 9,
    title: 'Plazma šejk',
    category: 'šejkovi',
    price: 350,
    img: './images/item-10.jpg',
    desc: `Retko koja osoba će odbiti plazmu, a najlepše piće od ovog keksa je svakako šejk. On se priprema od svega 3 namirnice.`,
  },
];
export default menu;
